# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dongliang Mu de Blog
email: mudongliangabcd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog Website For Information Security/System Security Student and Linuxer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mudongliang.github.io" # the base hostname & protocol for your site
twitter_username: mudongliang
github_username:  mudongliang

# Jekyll Plugins
plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown
